#!/bin/bash

if [ "$(id -u)" != "0" ]
then
     echo "This script must be run as root" 1>&2
     exit 1
fi

apt-get update
apt-get -y install ansible git
rm -rf /opt/anspull
git clone https://github.com/adrianrieck/anspull.git /opt/anspull
ansible-pull pbook.yml -d /opt/anspull -C master -U https://github.com/adrianrieck/anspull.git  -i /opt/anspull/inv.ini




