#!/bin/bash

repo_url='https://github.com/adrianrieck/anspull.git'
repo_dir='/opt/anspull'

if [ "$(id -u)" != "0" ]
then
     echo "This script must be run as root" 1>&2
     exit 1
fi

apt-get update
apt-get -y install ansible git
rm -rf $repo_dir
git clone $repo_url $repo_dir
ansible-pull pbook.yml -d $repo_dir -C master -U $repo_url  -i $repo_dir/inv.ini
