---

# Directives for all children nodes
- hosts: pi
  user: pi
  sudo: True
  sudo_user: root
  
  vars:
    playbook: pbook.yml
    cron_schedule: '*/30 * * * *'
    cron_user: root
    logfile: /var/log/ansible-pull.log
    repo_dir: /opt/anspull
    repo_url: https://github.com/adrianrieck/anspull.git
    lan_server_ip: 10.0.0.12
    adminuser: pi
    home: /home/pi


  tasks:
  #- name: Get RPI Serial
    #shell: awk '/Serial/{print $3}' /proc/cpuinfo
    #register: rpisn
    
  #- debug: msg="RPI Serial {{ rpisn.stdout }}"    
  
  - name: Create UUID file
    command: python -c "import uuid; print uuid.uuid4()," > {{ home }}/.uuid creates="{{ home }}"/.uuid
    
    
  - name: Get RPI UUID
    shell: cat {{ home }}/.uuid
    register: rpiuuid

  - debug: msg="RPI UUID {{ rpiuuid.stdout }}"    
  
  - name: Ensure curl is installed.
    apt: pkg=curl state=present update_cache=yes

  #- name: Ensure user adminuser is present.
    #user: name={{ adminuser }} state=present group=root groups="sudo" comment="managed account"
    
  #- name: Add configured user accounts to passwordless sudoers.
    #lineinfile:
      #dest: /etc/sudoers
      #regexp: '^{{ adminuser }}'
      #line: '{{ adminuser }} ALL=(ALL) NOPASSWD: ALL'
      #state: present
      #validate: 'visudo -cf %s'

  - name: Add Ansible Server Public Key to user adminuser
    authorized_key: user={{ adminuser }} key="{{ lookup('file', './files/ansible-server.pub') }}"
    
  - name: Create crontab entry to repeat ansible pull every hour
    template: src=templates/anscron.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644

  - name: Create logrotate entry for ansible-pull.log
    template: src=templates/anslogr.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644
    
  - name: Knock on LAN server
    command: curl http://{{ lan_server_ip }}/rpireg/sn-{{ rpiuuid.stdout }} creates=/opt/anspull/knock.done
