---

# Directives for all children nodes
- hosts: all
  user: pi
  sudo: True
  sudo_user: root
  
  vars:
  
  playbook : pbook.yml

  cron_schedule: '*/15 * * * *'

  cron_user: root

  logfile: /var/log/ansible-pull.log

  repo_dir: /opt/anspull

  repo_url: https://github.com/adrianrieck/anspull.git


  tasks:
  - name: Ensure vim is installed.
    apt: pkg=vim state=present update_cache=yes

  - name: Ensure user adminuser is present.
    user: name=adminuser state=present group=root

  - name: Placing key
    authorized_key: user=adminuser key="{{ lookup('file', './files/ansible-server.pub') }}"
